// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"database/sql"
	"github.com/rabbitmq/amqp091-go"
	"github.com/thangchung/go-coffeeshop/cmd/auth/config"
	"github.com/thangchung/go-coffeeshop/internal/auth/app/router"
	"github.com/thangchung/go-coffeeshop/internal/auth/domain"
	"github.com/thangchung/go-coffeeshop/internal/auth/infras/hasher"
	"github.com/thangchung/go-coffeeshop/internal/auth/infras/repo"
	"github.com/thangchung/go-coffeeshop/internal/auth/infras/token"
	"github.com/thangchung/go-coffeeshop/internal/auth/usecases/users"
	"github.com/thangchung/go-coffeeshop/internal/pkg/auth"
	"github.com/thangchung/go-coffeeshop/pkg/postgres"
	"github.com/thangchung/go-coffeeshop/pkg/rabbitmq"
	"github.com/thangchung/go-coffeeshop/pkg/rabbitmq/consumer"
	"github.com/thangchung/go-coffeeshop/pkg/rabbitmq/publisher"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventPublisher, err := publisher.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventConsumer, err := consumer.NewConsumer(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	db := sqlDBFunc(dbEngine)
	userRepository := repo.NewUserRepository(db)
	refreshTokenRepository := repo.NewRefreshTokenRepository(db)
	passwordHasher := hasherFunc()
	tokenGenerator := tokenGeneratorFunc(cfg)
	useCase := usecases.NewUserService(userRepository, refreshTokenRepository, passwordHasher, tokenGenerator)
	authServiceServer := router.NewAuthGRPCService(grpcServer, cfg, useCase)
	interceptor := authInterceptorFunc(tokenGenerator)
	app := New(cfg, dbEngine, connection, eventPublisher, eventConsumer, useCase, authServiceServer, interceptor)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, err
}

func sqlDBFunc(db postgres.DBEngine) *sql.DB {
	return db.GetDB()
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, err
}

func hasherFunc() domain.PasswordHasher {
	return hasher.NewBcryptHasher(0)
}

func tokenGeneratorFunc(cfg *config.Config) domain.TokenGenerator {
	return token.NewJWTTokenGenerator(cfg.JWT.SecretKey, cfg.JWT.Audience, cfg.JWT.Issuer)
}

func authInterceptorFunc(tokenGenerator domain.TokenGenerator) auth.Interceptor {
	publicMethods := []string{
		"/gen.AuthService/Login",
		"/gen.AuthService/Register",
		"/gen.AuthService/VerifyToken",
		"/gen.AuthService/RefreshToken",
	}
	return auth.NewInterceptor(tokenGenerator, publicMethods)
}
