// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"database/sql"

	"github.com/google/uuid"
)

type ProductProduct struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Type      int32        `json:"type"`
	Price     float64      `json:"price"`
	Stock     int32        `json:"stock"`
	Image     string       `json:"image"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
