// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, type, price, stock, image, created_at, updated_at FROM product.products WHERE id = ($1::uuid)
`

func (q *Queries) GetProductByID(ctx context.Context, dollar_1 uuid.UUID) (ProductProduct, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, dollar_1)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Price,
		&i.Stock,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsByNames = `-- name: GetProductsByNames :many
SELECT id, name, type, price, stock, image, created_at, updated_at FROM product.products WHERE name = ANY($1::text[])
`

func (q *Queries) GetProductsByNames(ctx context.Context, dollar_1 []string) ([]ProductProduct, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByNames, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductProduct
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, type, price, stock, image, created_at, updated_at FROM product.products
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductProduct, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductProduct
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Price,
			&i.Stock,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
