// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthPermission struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type AuthRefreshToken struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Token     string        `json:"token"`
	ExpiresAt time.Time     `json:"expires_at"`
	Revoked   sql.NullBool  `json:"revoked"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type AuthRole struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type AuthRolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type AuthUser struct {
	ID            uuid.UUID    `json:"id"`
	Email         string       `json:"email"`
	PasswordHash  string       `json:"password_hash"`
	IsActive      sql.NullBool `json:"is_active"`
	EmailVerified sql.NullBool `json:"email_verified"`
	LastLoginAt   sql.NullTime `json:"last_login_at"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type AuthUserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
