app:
  name: 'reverse-proxy'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 8000

grpc:
  product_host: '0.0.0.0'
  product_port: 8001
  counter_host: '0.0.0.0'
  counter_port: 8002
  auth_host: '0.0.0.0'
  auth_port: 8005

logger:
  log_level: 'debug'
  rollbar_env: 'reverse-proxy'