// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/thangchung/go-coffeeshop/cmd/product/config"
	"github.com/thangchung/go-coffeeshop/internal/product/app/router"
	"github.com/thangchung/go-coffeeshop/internal/product/infras/repo"
	"github.com/thangchung/go-coffeeshop/internal/product/usecases/products"
	"github.com/thangchung/go-coffeeshop/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	productRepo := repo.NewProductRepo(dbEngine)
	useCase := products.NewService(productRepo)
	productServiceServer := router.NewProductGRPCServer(grpcServer, useCase)
	app := New(cfg, useCase, productServiceServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
